//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBankApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ACCOUNT_HOLDER_DETAILS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT_HOLDER_DETAILS()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int ID { get; set; }
        public string account_number { get; set; }

        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Fullname { get; set; }
        public string Fathername { get; set; }
        public long Adharno { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime DOB { get; set; }
        public int Age { get; set; }
        public string accounttype { get; set; }
        public string Branch { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime Registration_Date { get; set; }
        public string Phoneno { get; set; }
        public Nullable<int> CusID { get; set; }
    
        public virtual User_Register User_Register { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
