//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBankApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeBankEntities12 : DbContext
    {
        public WeBankEntities12()
            : base("name=WeBankEntities12")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCOUNT_HOLDER_DETAILS> ACCOUNT_HOLDER_DETAILS { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Fund_Transfer> Fund_Transfer { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<User_Register> User_Register { get; set; }
    }
}
