//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeBankApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund_Transfer
    {
        public int ID { get; set; }
        public string Transaction_id { get; set; }
        public string account_number { get; set; }
        public string To_account_number { get; set; }
        public double amount { get; set; }
        public Nullable<int> TCCID { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
